name: golang
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - uses: actions/checkout@v4
    - run: go version
    - run: go mod verify
    - run: SKIP_FEATURE_TESTS=1 go test ./...
  godog-features:
    name: godog-features
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - uses: actions/checkout@v4
    - run: go test -v ./features
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - uses: actions/checkout@v4
    - uses: golangci/golangci-lint-action@v4
      with:
        version: 'v1.56.2'
